module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  auto_entitylabel: 0
  auto_entityqueue: 0
  automated_cron: 0
  block: 0
  breakpoint: 0
  bueditor: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  color: 0
  config: 0
  config_direct_save: 0
  config_filter: 0
  config_split: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_clone: 0
  entity_embed: 0
  entity_reference_number_widget: 0
  entity_reference_revisions: 0
  entityqueue: 0
  facets: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  forward: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  kint: 0
  link: 0
  media: 0
  media_entity_soundcloud: 0
  menu_ui: 0
  migrate: 0
  migrate_plus: 0
  migrate_tools: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  pathologic: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  search_api: 0
  search_api_db: 0
  search_api_pantheon: 0
  search_api_solr: 0
  search_kint: 0
  shortcut: 0
  simple_block: 0
  smtp: 0
  static_page: 0
  sw_admin_ui: 0
  sw_podcast: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  twig_tweak: 0
  update: 0
  user: 0
  video_embed_facebook: 0
  video_embed_field: 0
  video_embed_media: 0
  views_autocomplete_filters: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_contextual_filters_or: 0
  views_taxonomy_term_name_into_id: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  sw: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  revolution: 0
  sevenplus: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
