smtp_on: true
smtp_host: mail.gandi.net
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_username: website@socialistworker.org
smtp_password: ''
smtp_from: website@socialistworker.org
smtp_fromname: SocialistWorker.org
smtp_client_hostname: socialistworker.org
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
_core:
  default_config_hash: WEa5Ex_IeAcm6Bm0hmQ4vU_nDwJDB8hW-vxT1qpGIbM
